#----template code auto generated by fUICMaker!----#

#builtins
import sys, os
#3rd
from PyQt4 import QtCore, QtGui
#lib
from ui import mocapProjectCreatorUI as mocapprojectcreator


class DL_mocapProjectCreator(QtGui.QDialog, mocapprojectcreator.Ui_mocapProjectCreator):
    def __init__(self, parent=None):
        super(DL_mocapProjectCreator, self).__init__(parent)
        self.setupUi(self)
        self.input_str = ''
  
        #connections
        #attrs
        self.projectName_lineEdit.editingFinished.connect(self.projectName)
        
        
    #@QtCore.Slot()
    def projectName(self):
        input_str = self.projectName_lineEdit.text()
        if input_str == '':
            return
        self.projectName_lineEdit.w()  
         

    def _main(self):
        self.show()



#------------------------------------------------------------------------------
if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    dl = DL_mocapProjectCreator()
    dl._main()
    app.exec_()