#----template code auto generated by fUICMaker!----#

#builtins
import sys, os
#3rd
from PyQt4 import QtCore, QtGui
#lib
from ui import mocapProjectCreator as mocapprojectcreator


class DL_mocapProjectCreator(QtGui.QDialog, mocapprojectcreator.Ui_Dialog_mocapProjectCreator):
    def __init__(self, parent=None):
        super(DL_mocapProjectCreator, self).__init__(parent)
        self.setupUi(self)


        #connections
        #attrs

    def _main(self):
        self.show()



#------------------------------------------------------------------------------
if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    dl = DL_mocapProjectCreator()
    dl._main()
    app.exec_()