#----template code auto generated by fUICMaker!----#

#builtins
import sys, os
#3rd
from PyQt4 import QtCore, QtGui
#lib
from ui import renameTool_UI as renameui


class MW_m_renameTool(QtGui.QMainWindow, renameui.Ui_m_renameTool):
    def __init__(self, parent=None):
        super(MW_m_renameTool, self).__init__(parent)
        self.setupUi(self)


        #connections
        #attrs

    def _main(self):
        self.show()



#------------------------------------------------------------------------------
if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    mw = MW_m_renameTool()
    mw._main()
    app.exec_()